DROP DATABASE IF EXISTS todo_list;
CREATE DATABASE todo_list;

USE todo_list;

DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  descripcion TEXT,
  completed TINYINT NOT NULL DEFAULT 0,
  createt_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);